2020-09-17 14:40:33,072 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:40:34,196 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:40:43,172 ERROR: update failed originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:43:44,755 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:43:44,821 ERROR: update failed originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:44:30,198 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:44:30,421 ERROR: update failed originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:45:53,451 ERROR: update failed originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:46:37,300 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:46:38,972 ERROR: data is missing originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:47:02,143 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:47:27,485 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:48:27,985 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:48:36,016 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:48:55,058 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:48:58,977 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:49:55,244 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:50:39,464 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:51:17,384 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:51:22,982 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:52:36,728 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:52:47,169 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:53:59,894 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:54:01,071 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:54:13,699 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:55:20,256 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:55:21,407 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:55:23,110 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:56:39,364 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-17 14:57:03,124 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-17 14:58:00,528 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 13:58:23,903 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 13:58:25,212 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 13:59:33,947 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:01:51,615 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 14:02:07,632 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:02:28,291 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:04:39,227 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:05:27,722 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:07:27,018 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:18:52,248 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:20:24,655 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:20:51,841 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:21:16,137 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:21:31,550 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 14:21:39,847 ERROR: data is missing in the request originated in route: /capability_edit [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 15:37:00,505 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 15:42:45,153 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 15:56:00,598 ERROR: Student already exists! originated in route: /add_student [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 16:01:30,341 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:02:18,209 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:28:36,917 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:28:37,951 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:31:49,172 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:34:36,781 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:35:53,329 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:42:03,080 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:42:05,279 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:44:14,471 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:44:16,638 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:48:30,132 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:48:31,256 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:48:38,040 ERROR: db update failed originated in route: /delete_skill [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 16:50:41,746 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 16:50:52,263 ERROR: db update failed originated in route: /delete_skill [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
2020-09-18 16:51:55,107 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 17:18:57,998 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 17:18:59,075 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 17:22:23,536 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 17:22:25,579 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 17:24:34,039 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 17:28:19,357 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 17:28:20,660 INFO: server startup[in C:\Users\itpaz\KeeperHome\keepershomeserver\app\__init__.py:57]
2020-09-18 17:28:27,985 ERROR: cannot encode object: {'existing_skills.Transfiguration'}, of type: <class 'set'> originated in route: /delete_skill [in C:\Users\itpaz\KeeperHome\keepershomeserver\app\error_handler.py:43]
